"""create pharmacy requests

Revision ID: 0b1d2823540a
Revises: 5dfb1cf65b07
Create Date: 2026-08-27 16:36:19.651143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1d2823540a'
down_revision: Union[str, Sequence[str], None] = '5dfb1cf65b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_requests_id'), 'pharmacy_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_requests_status'), 'pharmacy_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pharmacy_requests_user_id'), 'pharmacy_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_requests_user_id'), table_name='pharmacy_requests')
    op.drop_index(op.f('ix_pharmacy_requests_status'), table_name='pharmacy_requests')
    op.drop_index(op.f('ix_pharmacy_requests_id'), table_name='pharmacy_requests')
    op.drop_table('pharmacy_requests')
    # ### end Alembic commands ###
