"""create pharmacy inventory

Revision ID: 3249580a3148
Revises: 7254a53a2605
Create Date: 2026-08-25 16:34:27.362317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3249580a3148'
down_revision: Union[str, Sequence[str], None] = '7254a53a2605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('pharmacy_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_users_id'), 'pharmacy_users', ['id'], unique=False)
    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'medicine_id', name='uq_pharmacy_medicine')
    )
    op.create_index(op.f('ix_pharmacy_inventory_id'), 'pharmacy_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_is_available'), 'pharmacy_inventory', ['is_available'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_medicine_id'), 'pharmacy_inventory', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_pharmacy_id'), 'pharmacy_inventory', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_medicines_category_id'), 'medicines', ['category_id'], unique=False)
    op.drop_constraint(op.f('medicines_category_id_fkey'), 'medicines', type_='foreignkey')
    op.create_foreign_key(None, 'medicines', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicines', type_='foreignkey')
    op.create_foreign_key(op.f('medicines_category_id_fkey'), 'medicines', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_medicines_category_id'), table_name='medicines')
    op.drop_index(op.f('ix_pharmacy_inventory_pharmacy_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_medicine_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_is_available'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_id'), table_name='pharmacy_inventory')
    op.drop_table('pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_users_id'), table_name='pharmacy_users')
    op.drop_table('pharmacy_users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
