"""create pharmacies

Revision ID: 7254a53a2605
Revises: 3f7783f6e9c2
Create Date: 2026-08-23 21:36:22.244278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7254a53a2605'
down_revision: Union[str, Sequence[str], None] = '3f7783f6e9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_city'), 'pharmacies', ['city'], unique=False)
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=False)
    op.create_index(op.f('ix_pharmacies_phone'), 'pharmacies', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacies_phone'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_city'), table_name='pharmacies')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
